version: "3.7"
services:
  db:
    container_name: pgsql
    image: postgres:13
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    expose:
      - 5432
    ports:
      - 5432:5432
  server:
    working_dir: "/usr/app/server"
    image: node:14
    volumes: 
      - "./server:/usr/app/server"
    ports:
      - 3000:3000
    command: ["npm", "run", "dev"]    
    env_file: 
      - ./server/env/development.env
  # client:
  #   working_dir: "/usr/app/client"
  #   image: node:14
  #   volumes:
  #     - "./client:/usr/app/client"
  #   ports:
  #     - 2999:3000
  #   command: ["npm", "start"]
  pg_admin:
    container_name: pgsql_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports: 
      - 3001:80
    logging: 
      driver: none