version: "3.7"
services:
  db:
    container_name: pgsql
    image: postgres:13
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    expose:
      - 5432
  server:
    working_dir: "/usr/src"
    image: node:14
    container_name: nodejs
    volumes: 
      - "./src:/usr/src"
    ports:
      - 3000:3000
    command: ["npm", "run"]    